import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex bg-white">
          <div className="w-60 bg-zinc-50 border-r border-zinc-200 overflow-auto shrink-0"></div>
          <div className="w-full pt-8 px-8">{children}</div>
        </main>
      </body>
    </html>
  );
}
